name: Generate Sitemap

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Add permissions block
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Updated version

      - name: Set up Python
        uses: actions/setup-python@v2  # Updated version
        with:
          python-version: '3.9'  # Specific Python version

      - name: List files (debugging)
        run: ls -l

      - name: Generate Sitemap
        run: |
          python generate_sitemap.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add sitemap.xml
          git commit -m "Auto-update sitemap"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
